rules = [
  OrganizeImports,
  DisableSyntax,
  RedundantSyntax
]

OrganizeImports {
  targetDialect = Scala3
  groups = ["re:javax?\\.", "scala.", "cats.", "fs2.", "*"]
  removeUnused = false
  blankLines = Manual
}

DisableSyntax {
  noVars = false
  noReturns = true
  noFinalize = true
  noXml = true
}
