# Scala Steward configuration
# https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md

# Pull requests
pullRequests.frequency = "7 days"
pullRequests.grouping = [
  { name = "all", filter = [{"group" = "*"}] }
]

# Limit concurrent PRs
updates.limit = 5
