package atn.mill

import utest.*

object PulumiModuleTest extends TestSuite {
  val tests = Tests {
    test("projectYaml renders a java runtime project pointing at the binary") {
      val yaml     = PulumiModule.projectYaml("infra", os.Path("/ws/out/pulumi/assembly.dest/out.jar"), Map.empty)
      val expected =
        """name: infra
          |runtime:
          |  name: java
          |  options:
          |    binary: /ws/out/pulumi/assembly.dest/out.jar
          |""".stripMargin
      assert(yaml == expected)
    }
    test("sdkPackageInfo reads name and version from the generated gradle files") {
      val settings    =
        """// *** WARNING: this file was generated by pulumi-java-gen. ***
          |pluginManagement { repositories { gradlePluginPortal() } }
          |
          |rootProject.name = "com.pulumi.iac-components"
          |""".stripMargin
      val buildGradle =
        """group = "com.pulumi"
          |
          |def resolvedVersion = System.getenv("PACKAGE_VERSION") ?:
          |    (project.version == "unspecified"
          |         ? "0.3.1"
          |         : project.version)
          |""".stripMargin
      val info        = PulumiModule.sdkPackageInfo(settings, buildGradle)
      assert(info == Some(PulumiModule.SdkPackageInfo("com/pulumi/iac-components", "iac-components", "0.3.1")))
    }
    test("sdkPackageInfo is empty when the gradle files are not recognisable") {
      assert(PulumiModule.sdkPackageInfo("", "") == None)
    }
    test("pluginJson matches what the generated gradle build writes") {
      val json     = PulumiModule.pluginJson(PulumiModule.SdkPackageInfo("com/pulumi/x", "iac-components", "0.3.1"))
      val expected =
        """{
          |    "resource": true,
          |    "name": "iac-components",
          |    "version": "0.3.1"
          |}""".stripMargin
      assert(json == expected)
    }
    test("projectYaml renders local packages sorted by name") {
      val yaml     = PulumiModule.projectYaml(
        "infra",
        os.Path("/ws/a.jar"),
        Map("zeta" -> "/ws/vendor/zeta", "iac-components" -> "/ws/vendor/iac-components")
      )
      val expected =
        """name: infra
          |runtime:
          |  name: java
          |  options:
          |    binary: /ws/a.jar
          |packages:
          |  iac-components: /ws/vendor/iac-components
          |  zeta: /ws/vendor/zeta
          |""".stripMargin
      assert(yaml == expected)
    }
  }
}
